### ISSUE TITLE
background-color is set overriding styles

### ISSUE THREAD

**Issue by simmel** [ptpb/pbs#2]
When using styles with ptpb `pbs.css` overrides the background-color of the style that you choose.

E.g. see https://ptpb.pw/NFIm/perl?style=vim

The background color of `pre` is set to `#f5f5f5` in `pbs.css` line 737. This overrides https://ptpb.pw/static/vim.css line 2.

I didn't find where the background color was set in less otherwise I would have PR'd it.

**Comment by buhman** [comment]
Yeah, I'm aware of this; I just never bothered to figure out how to fix it. The problem is the styles are shared with the index.rst rendering too, so just removing the `background-color` here could uglify things elsewhere.

> background color was set

Woops; https://github.com/ptpb/pbs/blob/master/src/less/pbs/code.less#L10

**Comment by buhman** [comment]
I think I might have reasonably-ish fixed this in https://github.com/ptpb/pbs/commit/103f9c6071296093886820fa3c00367e37bb95e8. That also removes the border though, which I think is less appealing than previously.
